import { Client, ClientPoints, Reward, Database, ClientType } from '../types';

const DB_KEY = 'gulf_prolub_db_v2'; // Incremented version to force refresh
const DEFAULT_POINTS = 0; 

const RAW_CLIENTS_CSV = `Tipo de cliente;Id;Punto de venta;Contraseña
Normal;3648;COLMENARES CELY MARIA DE JESUS;362
Normal;2288;TECNILUBRICANTES GYG S.A.S;167
Normal;2816;AGROFILTER LTDA;439
Normal;3415;SMART & GREEN ENERGY S.A.S.;402
Normal;7400;CARO CASTELBLANCO LUIS ALEJANDRO;178
Normal;9309;HUERTAS ORTEGA CESAR MANUEL;238
Normal;5663;JEREZ BUITRAGO JHON FREDY;223
Normal;3005;DACAR FILTROS S.A.S.;494
Normal;9643;PRIETO CARDENAS RONAL FABIAN;209
Normal;2744;ANAYA OLIVEROS DIANA FERNANDA;126
Normal;5489;FC POWER SOLUTIONS SAS;318
Normal;8915;SILVA VARGAS FABIO EDUARDO;126
Normal;7209;COMERCIALIZADORA FILT REP LTDA;463
Normal;2431;RIVAS MARTINEZ CARLOS EDUARDO;425
Normal;1358;MATALLANA BALLESTEROS MAURICIO ANTONIO;417
Normal;3886;DOSMOPAR SOCIEDAD POR ACCIONES SIMPLIFICADA;286
Normal;1533;MOLANO BARRIOS LAURA MELISSA;114
Normal;7869;GARCIA REYES GONZALO EDUARDO;179
Normal;1666;BERNAL PACHON GERMAN ALONSO;328
Normal;7882;LUBRISERVICIOS RETEN SUR S.A.S;350
Normal;2407;TECNI.MOTOS GL S.A.S.;284
Normal;7261;COMERCIALIZADORA INTERNACIONAL CALITRADE SOCIEDAD POR ACCIONES S;265
Normal;6100;AGROFILTRACIONES R.M. SAS;296
Normal;8254;FILTROS Y ACEITES SANTA MARTA S.A.S.;498
Normal;9279;GOMEZ RODRIGUEZ FERNANDO;376
Normal;3573;MELO OLMOS SERGIO ANDRES;442
Normal;3484;AMERICAN FILTERS OIL SAS;247
Normal;5373;ROZO MORA JORGE ALGEMIRO;297
Normal;8124;GRAND FILTERS EU;114
Normal;1370;CALDERON URREGO ANDRES ARTURO;313
Normal;4003;TECNIAUTOAMERICANA S.A.S.;388
Normal;9600;LUBRICANTES VALLADOLID S.A.S.;417
Normal;3582;COLOMBIANA DE ACEITES Y FILTROS INDUSTRIALES S.A.S;368
Normal;6150;ROJAS PEREZ JOSE ORLANDO;278
Normal;5306;BRAVO GRISALES LUZ DERLY;221
Normal;2444;PIRACOCA JIMENEZ HECTOR EMILIO;105
Normal;9766;GUALTEROS LOVERA FERNANDO;225
Normal;1561;MURCIA ALBORNOZ JUAN PABLO;137
Normal;6041;LUBRICANTES GARCIA NOPE SAS;156
Normal;5451;DONDE ALEJO LUBRICENTRO SAS;231
Normal;5102;CORO JORGE IVAN;344
Normal;5898;PAULO RICHARD RAMOS DAZA;257
Normal;9856;OSCAR FERNANDO PEÑA GUTIERREZ;446
Normal;1625;GOMEZ CERON ARCELINA MARGOTH;133
Normal;3861;SUAREZ OJEDA IVAN RICARDO;440
Normal;2618;RAMIREZ MIRQUEZ MOISES;149
Normal;5535;SILVA LOPEZ OSCAR IVAN;257
Normal;2253;HERNANDEZ SACRISTAN FABIAN ROLANDO;136
Normal;1968;SALINAS REYES GESLY YURANY;308
Normal;1621;BIOFILTER LTDA;174
Normal;4791;RODRIGUEZ PULIDO LUZ DARY;411
Normal;4290;QUINTANA RIASCOS JOSE FERNANDO;330
Normal;2335;MONTACARGAS EN SIBERIA S A S;351
Normal;4435;LUBRICANTES LA ROCA S.A.S;229
Normal;2720;DOCEL RAMIREZ JUAN CARLOS;210
Normal;1886;SANCHEZ PALACIO ANGEL HUMBERTO;443
Normal;4368;LUBRICANTES Y FILTROS LA SEXTA AVENIDA S.A.S.;163
Normal;9164;MASFILTER Y LUBRICANTES SAS;115
Normal;6783;DIRECCIONES HIDRAULICAS EL MONO SAS;317
Normal;1069;JARAMILLO QUINTERO JAIRO;474
Normal;1055;FIZA S A S;296
Normal;5963;VALLES ABELLO ARMANDO;208
Normal;3051;LUBRIMOTOR GRASAS Y ACEITES S.A.S LUBRIMOTOR S.A.S;260
Normal;1247;PEREZ BAUTISTA FRANCISCO ALEJANDRO;253
Normal;8989;GONZALEZ MATAMOROS MARIA DEL TRANSITO;441
Normal;8437;DISTRIBUIDORA DE FILTROS Y LUBRICANTES SR LTDA;104
Normal;7501;PARADA BEATRIZ;480
Normal;7247;GALARZA CARDONA ANDRES FELIPE;446
Normal;6276;RODRIGUEZ TROCHEZ ENELIA;175
Normal;1202;LUBRICENTRO SANTA ROSA SAS;364
Normal;8287;ALBERTO TORRES CARLOS ALFREDO;294
Normal;8658;DIAZ PINZON LUIS FERNANDO;296
Normal;4896;TRANSPORTES Y SERVICIOS INTEGRAL S.A.S;120
Normal;4658;ELECTRICOS Y FERRETERIA GERVEL & COMPAÑIA LTDA;193
Normal;3629;MERCADO RAMIREZ JHON WAYNER;454
Normal;6542;FILTROS Y LUBRICANTES H Y H SAS;148
Normal;8832;VILLANUEVA JAMIR;155
Normal;1922;S.S. UP INVERSIONES SAS;300
Normal;9997;G & O CAMBIO Y DISTRIBUCION DE ACEITE MONTALLANTAS SAS;174
Normal;2810;COMERCIALIZADORA FILT REP LTDA;189
Normal;7887;ESCOBAR CARDONA CESAR AUGUSTO;166
Normal;9054;HERNANDO RINCON CABRA;403
Normal;3330;CASA DEL FILTRO CHÍA S.A.S;430
Normal;3984;RINCON MORENO BRAYAN EDUARDO;477
Normal;7129;LUBRIMARKET FILTROS Y LUBRICANTES SAS;380
Normal;7515;AREVALO CABRA WILMER;489
Normal;9702;TRATERCOL INGENIERIA DE TRATAMIENTOS TERMICOS S.A.S.;395
Normal;8403;MORALES MARTINEZ LEIDY MARCELA;392
Normal;2884;REPRESENTANTE SEGURIDAD GAS S. A. S.;491
Normal;2589;GUERRERO DIAZ CARLOS AUGUSTO;302
Normal;1452;INDUSTRIAS CARDENAS FIRE SAS;435
Normal;6586;SALAS ROSERO EDITH LUCIA;197
Normal;2378;FERRETERIA INDUSTRIAL SOLUFER S.A.S.;282
Normal;6216;LINARES CABRA RUTH ADRIANA;395
Normal;2253;RODRIGUEZ PULIDO ANA BELISA;280
Normal;3795;ALVAREZ RUIZ LILIANA;295
Normal;8697;TECNOLUBES SAS;222
Normal;7064;CRUZ AVILA JOSE JOAQUIN;307
Normal;6295;ZAPATA GIRALDO MARTHA ROCIO;373
Normal;4343;CIFUENTES SABOGAL PLUTARCO;327
Normal;5266;MONTES GUILLERMO ALVARO JOSE;321
Normal;3497;CORTES SANCHEZ GUSTAVO ADOLFO;183
Normal;8886;PEREZ SEGURA JOSE EDUARDO;435
Normal;7761;CENTRO DE MANTENIMIENTO AUTOMOTRIZ RD S.A.S.;275
Normal;3616;COOPERATIVA DE TRANSPORTADORES FLOTA PALMIRA;105
Normal;9104;DISTRIGAUSDA SAS;349
Normal;5834;MOLINA TORRES NIDIA ESPERANZA;243
Normal;1462;RIGO AUTOS CALI S.A.S;165
Normal;4743;SERVITECA LUBRITECA 15 B S.A.S.;159
Normal;6132;MERLO VANEGAS FLOR CRISTINA;320
Normal;8399;CERON BUITRON PASTOR;133
Normal;9577;LYC LUBRICANTES SAS;292
Normal;3880;PRIETO CANTE CRISTIAN CAMILO;122
Normal;4854;LOPEZ DIAZ GUSTAVO;250
Normal;9881;HERNANDEZ ORTIZ LISSETTE;133
Normal;3978;ROJAS GUATUSMAL BRENDA JOHANA;122
Normal;2941;RIVERA BRAVA S.A.S.;321
Normal;4619;OCAMPO BARRAGAN YESMIN CRISTINA;361
Normal;3645;BECERRA LEON LUZ DARY;439
Normal;2456;TRIANA ROJAS ANA CLOVIS;392
Normal;3169;MUNDIAL DE FILTROS Y AUTOPARTESSAGA SAS;288
Normal;8975;BEJARANO RAMOS LUZ ANGELICA;277
Normal;9874;SERVICIOS INTEGRALES EN LUBRICACIÓN DE MAQUINARIA S.A.S.;481
Normal;5859;BAREÑO FRANCO ELVER RICARDO;496
Normal;5634;GUZMAN GOMEZ NESTOR DARIO;477
Normal;1276;NEWMAN´S CARS SAS;421
Normal;8593;SAAVEDRA GONZALEZ JHON JAIRO;337
Normal;3951;SU PROVEEDOR SUMINISTROS Y FERRETERIA S.A.S;378
Normal;2093;ARIESCA FILTROS & LUBRICANTES S.A.S;458
Normal;7655;DAZA GOMEZ JONATHAN SMITH;430
Normal;1644;RINCON RIVEROS ORLANDO;411
Normal;1139;GONZALEZ SALINAS JEIMMY CAROLINA;109
Normal;7395;HIDRAULICOS J R S A S;413
Normal;6673;AUTOPARTES J&M SUÁREZ S.A.S;335
Normal;3925;HC SERVICE ´S SAS;418
Normal;5440;FORTALEZA CENTRO DE LUBRICACION SAS;466
Normal;5378;ZAPATA GAMBINO WILSON JAVIER;417
Normal;9175;GOMEZ ESPITIA NELSON ARMANDO;451
Normal;6885;TRANSPORTES LIMICIO LTDA;161
Normal;1135;AGROFILTER DE LA SABANA SAS;194
Normal;3829;GUTIERREZ ROJAS JOHAN FELIPE;395
Normal;9771;LEON MOYANO JAVIER MAURICIO;373
Normal;2688;LUBRICANTES SAN ANTONIO SAS;305
Normal;9084;OCCIDENTAL DE SERVICIOS Y REPUESTOS AAA SAS;315
Normal;9493;GALEANO VELASQUEZ MARIA DACIER;145
Normal;4604;RAUL CASAÑAS PALACIOS;377
Normal;6131;FLOREZ VENEGAS JUAN CARLOS;398
Normal;8742;SIERRA MARTINEZ JOHN ALEJANDRO;460
Normal;9905;VILLAMIL MARTINEZ JONATHAN;495
Normal;5078;ABASTECEDORA NACIONAL DE ESTIBAS ANALDES S A;401
Normal;3026;HERNANDEZ NIÑO LEOPOLDO;387
Normal;4045;EDS TISQUESUSA S.A.S;412
Normal;3837;VARGAS VASQUEZ MARY LUZELLA;237
Normal;9146;MORALES GONZALEZ OCTAVIO;154
Normal;4337;PRADA EDWIN CAMILO;481
Normal;1480;TORNIFRENOS Y REPUESTOS OSORIO S.A.S.;248
Normal;3793;RODRIGUEZ QUIROGA JOSE ALEXANDER;197
Normal;1479;GUZMAN ROJAS JUAN SEBASTIAN;128
Normal;6714;RODRIGUEZ ROMERO TANIA MARCELA;171
Normal;3901;GOMEZ LEDESMA LUIS ARMANDO;356
Normal;2614;COLOMBIANA DISTRIBUIDORA DE LUBRICANTES SAS;121
Normal;4187;CRUZ OCHOA JULIO CESAR;394
Normal;7573;LUBRICANTES Y BATERIAS WILCARS SAS;134
Normal;2321;CAPERA LIDIA;221
Normal;2443;SALDARRIAGA & CIA LTDA;129
Normal;2991;CAICEDO CAÑON INGRID MADALAIN;178
Normal;9218;INSTITUTO TECNICO DE EDUCACION LABORAL Y MECANICO DE OCCIDENTE S;236
Normal;6403;GONZALEZ SUAREZ LUIS ALFREDO;435
Normal;1646;VISUM Y CIA LTDA;404
Normal;6401;TRUCK FILERS JM S.A.S;185
Normal;5581;QUINTERO KAREN ARABELLY;427
Normal;3488;NIÑO ZAPATA BRYANT ESTIVEN;143
Normal;6602;BOBCAT SERVICE SAS;214
Normal;2901;ARMERO MORALES SANDRA MILENA;210
Normal;4393;TIBAVISCO VELOZA SERGIO LEONARDO;336
Normal;9719;FILTROS AYZ S.A.S.;336
Normal;1211;PARRA GOMEZ SERGIO GIOVANY;324
Normal;9164;NEIRA LOPEZ LEONARDO MIGUEL;245
Normal;4480;NELCAR DE OCCIDENTE S.A.S;120
Normal;6361;VARGAS MARTINEZ ISMAEL ANTONIO;404
Normal;8314;CENTRO DE LUBRICACION AUTOMOTRIZ S.A.S.;375
Normal;7680;DIAZ MORENO OLGA PATRICIA;312
Normal;5630;TORRES MORALES PAOLA ANDREA;315
Normal;3115;BARRETO OCHOA ROBERT ALBERTO;347
Normal;3234;RODRIGUEZ SILVA JAZMIN LORENA;468
Normal;8959;BAQUERO LARA SILVIA NOHELBA;477
Normal;6465;NUÑEZ MONROY ARMANDO;281
Normal;4844;RODRIGUEZ BONILLA SORAIDA;452
Normal;3291;LUBRIMARKAS R&D S.A.S;211
Normal;5061;GARCIA MARTINEZ EDWIN ALEXANDER;402
Normal;2538;DAZA BARBOSA CRISTIAN CAMILO;352
Normal;5338;CUTA QUINTANA PEDRO ALONSO;153
Normal;2709;MONGUI MEDINA JUAN CARLOS;229
Normal;5984;SANCHEZ BARON MIGUEL ANTONIO;115
Normal;8790;CARDENAS LOPEZ VIVIANA ANDREA;282
Normal;7453;GUZMAN PINEDA YENIFFER;484
Normal;1398;ALONSO GONZALEZ GONZALEZ;414
Normal;2245;LOPEZ GONZALEZ LUIS FERNANDO;299
Normal;3397;PANQUEVA MONTOYA PATRICIO JAVIER;184
Normal;4998;RINCON MONTOYA NELSON ENRIQUE;427
Normal;1899;SANCHEZ AMAGUAÑA FABIAN JAIR;136
Normal;5812;MONTACARGAS HARD CARGO SAS;107
Normal;9261;MKTRONICA CAR SERVICE S.A.S;316
Normal;3827;SERRANO CELY VELKYS SARIMA;273
Normal;2520;AREVALO LOPEZ WALTER;395
Normal;9304;OPERADOR LOGISTICO DG S.A.S;421
Normal;9959;GUAYACAN GUEVARA ALBA INES;342
Normal;4546;VARGAS GONZALEZ LUIS NELSON;319
Normal;8115;SILVA BARBOSA BRIYITH NATALY;423
Normal;4963;CONTRERAS MORENO LUZ ANGELA;342
Normal;9699;TECNIPLANTAS AIRES Y BOMBAS SAS;137
Normal;8419;LOSADA VALLEJO NICXON ALEJANDRO;332
Normal;5145;MONTAÑO BAHAMON JULIAN DAVID;280
Normal;6365;GOMEZ SALAZAR JOHN EDGAR;127
Normal;8972;QUIROGA LEON RUTH NEYLA;406
Normal;5982;ESCOBAR FRANCO JORGE HERMINSUL;172
Normal;8032;GALINDO JULIO CESAR;203
Normal;5534;GOMEZ MESSA JULIAN;221
Normal;6735;GALEANO ALARCON MARCELA;268
Normal;6169;CARDENAS MUÑOZ FLOR DE MARIA;474
Normal;5726;MORENO CABALLERO NINA;286
Normal;2916;CASTRO PARADA HELMER ERNESTO;402
Normal;7844;LOSADA PACHON JOSE DANIEL;445
Normal;7095;ARAGON HENAO FERNANDO ANDRES;146
Normal;3527;ZAMORA VASQUEZ ELIECER;192
Normal;1417;CUEVAS RODRIGUEZ YESID ADRIAN;474
Normal;9031;LUBRIFILTROS MJ SAS;261
Normal;5549;UMAÑA MARTINEZ VICTOR SAMIR;309
Normal;9949;SERVICIOS AUTOMOTORES FLORIDA S.A.S.;387
Normal;8166;FERNANDEZ PAYA ROSO FRANCISCO;457
Normal;1094;NIETO SOLANO LIZETH PAOLA;261
Normal;7012;GONZALEZ SANNA ERICK;356
Normal;9608;BENAVIDES SIERRA DANIEL ANDRES;283
Normal;4532;AUTOVOL PROFESSIONAL S.A.S;493
Normal;5090;LUBRICANTES G.V. SAS;261
Normal;7795;MORENO CUCAITA JHON FREDDY;316
Normal;1766;QUIROGA PAEZ NORBEY ALBERTO;158
Normal;3289;AYALA BERNAL JOSE MESIAS;136
Normal;6776;SERVITECH GROUP SAS;232
Normal;9300;LOPEZ FORERO CRISTIAN CAMILO;127
Pareto;4781;LUBRICANTES LA ESTRELLA FACA S.A.S.;701
Pareto;2842;COOPERATIVA VALLECAUCANA DE TRANSPORTADORES;855
Pareto;7436;LUBRICANTES CZ S.A.S.;558
Pareto;3141;FILTROS Y FILTROS S.A.S.;800
Pareto;6102;GRISALES MESA EDWARD HERNAN;637
Pareto;6761;ROMERO BONILLA MARIN;535
Pareto;9598;DISTRIBUIDORA HERCA ASOCIADOS SAS;951
Pareto;5628;COOPERATIVA INTEGRAL DE TRANSPORTADORES TAXIS EL TRIUNFO;501
Pareto;5953;HOLGIN DIAZ ADALBERTO;822
Pareto;8458;WM FILTERS SAS;961
Pareto;9951;FILCENTER S A S;959
Pareto;5891;PRO-MOTORS S A S;740
Pareto;8677;PEREZ PLAZAS YILMER;538
Pareto;8170;LUBRIREPUESTOS YUMBO JRC S.A.S;723
Pareto;4397;RATIVA ORLANDO ALBERTO;795
Pareto;1142;TRACTOCAD S EN C S;777
Pareto;4517;AMAYA BERNAL VICTOR ANTONIO;930
Pareto;9097;GOMEZ CERON LUDIVIA;874
Pareto;2071;DISTRIBUCIONES ALVARO CORREA S.A.S.;747
Pareto;7832;LUBRICANTES PEPO S.A.S;697
Pareto;8143;INDUSTRIA SUPERFILT S.A.S;909
Pareto;7191;CERON OCHOA MAGNOLIA;912
Pareto;2133;LUBRICANTES Y FILTROS J J S.A.S;857
Pareto;9931;DISTRIBUIDORA IMALBESTOS SAS;823
Pareto;2822;LUBRIKARS S.A.S;604
Pareto;2799;VELASCO VEGA AURA STELLA;858
Pareto;2929;MAX OIL SAS;597
Pareto;5550;GASODISEL SABANA S.A.S;870
Pareto;2468;G C FILTERS SAS;530
Pareto;3793;GONZALEZ SALINAS EDWIN ARLEY;558
Pareto;6300;LUBRIPARTS LYL S.A.S;891
Pareto;6800;AUTOFILTROS Y PARTES GONZA MOTORS SAS;807
Pareto;4374;SERVILLANTAS JAMUNDI S.A.S;745
Pareto;4903;INGEFILTERS COLOMBIA SAS;885
Pareto;9808;HERRERA QUINTERO VICTOR ALONSO;684
Pareto;3237;LUBRICANTES DIDAMAR S.A.S;749
Pareto;3456;VARGAS SALAMANCA LUIS ANGEL;927
Pareto;9790;MARTEXA C I S A S;920
Pareto;7561;DACAR FILTROS S.A.S.;978
Pareto;6931;INVERSIONES BOGOTA MOTORS SAS;876
Pareto;9731;IBAÑEZ ALFONSO EFRAIN;821`;

const RAW_POINTS_CSV = `Punto de venta;Puntos disponibles
COLMENARES CELY MARIA DE JESUS;10
TECNILUBRICANTES GYG S.A.S;10
AGROFILTER LTDA;10
SMART & GREEN ENERGY S.A.S.;10
CARO CASTELBLANCO LUIS ALEJANDRO;10
HUERTAS ORTEGA CESAR MANUEL;10
JEREZ BUITRAGO JHON FREDY;10
DACAR FILTROS S.A.S.;10
PRIETO CARDENAS RONAL FABIAN;10
ANAYA OLIVEROS DIANA FERNANDA;10
FC POWER SOLUTIONS SAS;10
SILVA VARGAS FABIO EDUARDO;10
COMERCIALIZADORA FILT REP LTDA;10
RIVAS MARTINEZ CARLOS EDUARDO;10
MATALLANA BALLESTEROS MAURICIO ANTONIO;10
DOSMOPAR SOCIEDAD POR ACCIONES SIMPLIFICADA;10
MOLANO BARRIOS LAURA MELISSA;10
GARCIA REYES GONZALO EDUARDO;10
BERNAL PACHON GERMAN ALONSO;10
LUBRISERVICIOS RETEN SUR S.A.S;10
TECNI.MOTOS GL S.A.S.;10
COMERCIALIZADORA INTERNACIONAL CALITRADE SOCIEDAD POR ACCIONES S;10
AGROFILTRACIONES R.M. SAS;10
FILTROS Y ACEITES SANTA MARTA S.A.S.;10
GOMEZ RODRIGUEZ FERNANDO;10
MELO OLMOS SERGIO ANDRES;10
AMERICAN FILTERS OIL SAS;10
ROZO MORA JORGE ALGEMIRO;10
GRAND FILTERS EU;10
CALDERON URREGO ANDRES ARTURO;10
TECNIAUTOAMERICANA S.A.S.;10
LUBRICANTES VALLADOLID S.A.S.;10
COLOMBIANA DE ACEITES Y FILTROS INDUSTRIALES S.A.S;10
ROJAS PEREZ JOSE ORLANDO;10
BRAVO GRISALES LUZ DERLY;10
PIRACOCA JIMENEZ HECTOR EMILIO;10
GUALTEROS LOVERA FERNANDO;10
MURCIA ALBORNOZ JUAN PABLO;10
LUBRICANTES GARCIA NOPE SAS;10
DONDE ALEJO LUBRICENTRO SAS;10
CORO JORGE IVAN;10
PAULO RICHARD RAMOS DAZA;10
OSCAR FERNANDO PE A GUTIERREZ;10
GOMEZ CERON ARCELINA MARGOTH;10
SUAREZ OJEDA IVAN RICARDO;10
RAMIREZ MIRQUEZ MOISES;10
SILVA LOPEZ OSCAR IVAN;10
HERNANDEZ SACRISTAN FABIAN ROLANDO;10
SALINAS REYES GESLY YURANY;10
BIOFILTER LTDA;10
RODRIGUEZ PULIDO LUZ DARY;10
QUINTANA RIASCOS JOSE FERNANDO;10
MONTACARGAS EN SIBERIA S A S;10
LUBRICANTES LA ROCA S.A.S;10
DOCEL RAMIREZ JUAN CARLOS;10
SANCHEZ PALACIO ANGEL HUMBERTO;10
LUBRICANTES Y FILTROS LA SEXTA AVENIDA S.A.S.;10
MASFILTER Y LUBRICANTES SAS;10
DIRECCIONES HIDRAULICAS EL MONO SAS;10
JARAMILLO QUINTERO JAIRO;10
FIZA S A S;10
VALLES ABELLO ARMANDO;10
LUBRIMOTOR GRASAS Y ACEITES S.A.S LUBRIMOTOR S.A.S;10
PEREZ BAUTISTA FRANCISCO ALEJANDRO;10
GONZALEZ MATAMOROS MARIA DEL TRANSITO;10
DISTRIBUIDORA DE FILTROS Y LUBRICANTES SR LTDA;10
PARADA BEATRIZ;10
GALARZA CARDONA ANDRES FELIPE;10
RODRIGUEZ TROCHEZ ENELIA;10
LUBRICENTRO SANTA ROSA SAS;10
ALBERTO TORRES CARLOS ALFREDO;10
DIAZ PINZON LUIS FERNANDO;10
TRANSPORTES Y SERVICIOS INTEGRAL S.A.S;10
ELECTRICOS Y FERRETERIA GERVEL & COMPA IA LTDA;10
MERCADO RAMIREZ JHON WAYNER;10
FILTROS Y LUBRICANTES H Y H SAS;10
VILLANUEVA JAMIR;10
S.S. UP INVERSIONES SAS;10
G & O CAMBIO Y DISTRIBUCION DE ACEITE MONTALLANTAS SAS;10
COMERCIALIZADORA FILT REP LTDA;10
ESCOBAR CARDONA CESAR AUGUSTO;10
HERNANDO RINCON CABRA;10
CASA DEL FILTRO CH A S.A.S;10
RINCON MORENO BRAYAN EDUARDO;10
LUBRIMARKET FILTROS Y LUBRICANTES SAS;10
AREVALO CABRA WILMER;10
TRATERCOL INGENIERIA DE TRATAMIENTOS TERMICOS S.A.S.;10
MORALES MARTINEZ LEIDY MARCELA;10
REPRESENTANTE SEGURIDAD GAS S. A. S.;10
GUERRERO DIAZ CARLOS AUGUSTO;10
INDUSTRIAS CARDENAS FIRE SAS;10
SALAS ROSERO EDITH LUCIA;10
FERRETERIA INDUSTRIAL SOLUFER S.A.S.;10
LINARES CABRA RUTH ADRIANA;10
RODRIGUEZ PULIDO ANA BELISA;10
ALVAREZ RUIZ LILIANA;10
TECNOLUBES SAS;10
CRUZ AVILA JOSE JOAQUIN;10
ZAPATA GIRALDO MARTHA ROCIO;10
CIFUENTES SABOGAL PLUTARCO;10
MONTES GUILLERMO ALVARO JOSE;10
CORTES SANCHEZ GUSTAVO ADOLFO;10
PEREZ SEGURA JOSE EDUARDO;10
CENTRO DE MANTENIMIENTO AUTOMOTRIZ RD S.A.S.;10
COOPERATIVA DE TRANSPORTADORES FLOTA PALMIRA;10
DISTRIGAUSDA SAS;10
MOLINA TORRES NIDIA ESPERANZA;10
RIGO AUTOS CALI S.A.S;10
SERVITECA LUBRITECA 15 B S.A.S.;10
MERLO VANEGAS FLOR CRISTINA;10
CERON BUITRON PASTOR;10
LYC LUBRICANTES SAS;10
PRIETO CANTE CRISTIAN CAMILO;10
LOPEZ DIAZ GUSTAVO;10
HERNANDEZ ORTIZ LISSETTE;10
ROJAS GUATUSMAL BRENDA JOHANA;10
RIVERA BRAVA S.A.S.;10
OCAMPO BARRAGAN YESMIN CRISTINA;10
BECERRA LEON LUZ DARY;10
TRIANA ROJAS ANA CLOVIS;10
MUNDIAL DE FILTROS Y AUTOPARTESSAGA SAS;10
BEJARANO RAMOS LUZ ANGELICA;10
SERVICIOS INTEGRALES EN LUBRICACI N DE MAQUINARIA S.A.S.;10
BARE O FRANCO ELVER RICARDO;10
GUZMAN GOMEZ NESTOR DARIO;10
NEWMAN S CARS SAS;10
SAAVEDRA GONZALEZ JHON JAIRO;10
SU PROVEEDOR SUMINISTROS Y FERRETERIA S.A.S;10
ARIESCA FILTROS & LUBRICANTES S.A.S;10
DAZA GOMEZ JONATHAN SMITH;10
RINCON RIVEROS ORLANDO;10
GONZALEZ SALINAS JEIMMY CAROLINA;10
HIDRAULICOS J R S A S;10
AUTOPARTES J&M SU REZ S.A.S;10
HC SERVICE  S SAS;10
FORTALEZA CENTRO DE LUBRICACION SAS;10
ZAPATA GAMBINO WILSON JAVIER;10
GOMEZ ESPITIA NELSON ARMANDO;10
TRANSPORTES LIMICIO LTDA;10
AGROFILTER DE LA SABANA SAS;10
GUTIERREZ ROJAS JOHAN FELIPE;10
LEON MOYANO JAVIER MAURICIO;10
LUBRICANTES SAN ANTONIO SAS;10
OCCIDENTAL DE SERVICIOS Y REPUESTOS AAA SAS;10
GALEANO VELASQUEZ MARIA DACIER;10
RAUL CASA AS PALACIOS;10
FLOREZ VENEGAS JUAN CARLOS;10
SIERRA MARTINEZ JOHN ALEJANDRO;10
VILLAMIL MARTINEZ JONATHAN;10
ABASTECEDORA NACIONAL DE ESTIBAS ANALDES S A;10
HERNANDEZ NI O LEOPOLDO;10
EDS TISQUESUSA S.A.S;10
VARGAS VASQUEZ MARY LUZELLA;10
MORALES GONZALEZ OCTAVIO;10
PRADA EDWIN CAMILO;10
TORNIFRENOS Y REPUESTOS OSORIO S.A.S.;10
RODRIGUEZ QUIROGA JOSE ALEXANDER;10
GUZMAN ROJAS JUAN SEBASTIAN;10
RODRIGUEZ ROMERO TANIA MARCELA;10
GOMEZ LEDESMA LUIS ARMANDO;10
COLOMBIANA DISTRIBUIDORA DE LUBRICANTES SAS;10
CRUZ OCHOA JULIO CESAR;10
LUBRICANTES Y BATERIAS WILCARS SAS;10
CAPERA LIDIA;10
SALDARRIAGA & CIA LTDA;10
CAICEDO CA ON INGRID MADALAIN;10
INSTITUTO TECNICO DE EDUCACION LABORAL Y MECANICO DE OCCIDENTE S;10
GONZALEZ SUAREZ LUIS ALFREDO;10
VISUM Y CIA LTDA;10
TRUCK FILERS JM S.A.S;10
QUINTERO KAREN ARABELLY;10
NI O ZAPATA BRYANT ESTIVEN;10
BOBCAT SERVICE SAS;10
ARMERO MORALES SANDRA MILENA;10
TIBAVISCO VELOZA SERGIO LEONARDO;10
FILTROS AYZ S.A.S.;10
PARRA GOMEZ SERGIO GIOVANY;10
NEIRA LOPEZ LEONARDO MIGUEL;10
NELCAR DE OCCIDENTE S.A.S;10
VARGAS MARTINEZ ISMAEL ANTONIO;10
CENTRO DE LUBRICACION AUTOMOTRIZ S.A.S.;10
DIAZ MORENO OLGA PATRICIA;10
TORRES MORALES PAOLA ANDREA;10
BARRETO OCHOA ROBERT ALBERTO;10
RODRIGUEZ SILVA JAZMIN LORENA;10
BAQUERO LARA SILVIA NOHELBA;10
NU EZ MONROY ARMANDO;10
RODRIGUEZ BONILLA SORAIDA;10
LUBRIMARKAS R&D S.A.S;10
GARCIA MARTINEZ EDWIN ALEXANDER;10
DAZA BARBOSA CRISTIAN CAMILO;10
CUTA QUINTANA PEDRO ALONSO;10
MONGUI MEDINA JUAN CARLOS;10
SANCHEZ BARON MIGUEL ANTONIO;10
CARDENAS LOPEZ VIVIANA ANDREA;10
GUZMAN PINEDA YENIFFER;10
ALONSO GONZALEZ GONZALEZ;10
LOPEZ GONZALEZ LUIS FERNANDO;10
PANQUEVA MONTOYA PATRICIO JAVIER;10
RINCON MONTOYA NELSON ENRIQUE;10
SANCHEZ AMAGUA A FABIAN JAIR;10
MONTACARGAS HARD CARGO SAS;10
MKTRONICA CAR SERVICE S.A.S;10
SERRANO CELY VELKYS SARIMA;10
AREVALO LOPEZ WALTER;10
OPERADOR LOGISTICO DG S.A.S;10
GUAYACAN GUEVARA ALBA INES;10
VARGAS GONZALEZ LUIS NELSON;10
SILVA BARBOSA BRIYITH NATALY;10
CONTRERAS MORENO LUZ ANGELA;10
TECNIPLANTAS AIRES Y BOMBAS SAS;10
LOSADA VALLEJO NICXON ALEJANDRO;10
MONTA O BAHAMON JULIAN DAVID;10
GOMEZ SALAZAR JOHN EDGAR;10
QUIROGA LEON RUTH NEYLA;10
ESCOBAR FRANCO JORGE HERMINSUL;10
GALINDO JULIO CESAR;10
GOMEZ MESSA JULIAN;10
GALEANO ALARCON MARCELA;10
CARDENAS MU OZ FLOR DE MARIA;10
MORENO CABALLERO NINA;10
CASTRO PARADA HELMER ERNESTO;10
LOSADA PACHON JOSE DANIEL;10
ARAGON HENAO FERNANDO ANDRES;10
ZAMORA VASQUEZ ELIECER;10
CUEVAS RODRIGUEZ YESID ADRIAN;10
LUBRIFILTROS MJ SAS;10
UMA A MARTINEZ VICTOR SAMIR;10
SERVICIOS AUTOMOTORES FLORIDA S.A.S.;10
FERNANDEZ PAYA ROSO FRANCISCO;10
NIETO SOLANO LIZETH PAOLA;10
GONZALEZ SANNA ERICK;10
BENAVIDES SIERRA DANIEL ANDRES;10
AUTOVOL PROFESSIONAL S.A.S;10
LUBRICANTES G.V. SAS;10
MORENO CUCAITA JHON FREDDY;10
QUIROGA PAEZ NORBEY ALBERTO;10
AYALA BERNAL JOSE MESIAS;10
SERVITECH GROUP SAS;10
LOPEZ FORERO CRISTIAN CAMILO;10
LUBRICANTES LA ESTRELLA FACA S.A.S.;10
COOPERATIVA VALLECAUCANA DE TRANSPORTADORES;10
LUBRICANTES CZ S.A.S.;10
FILTROS Y FILTROS S.A.S.;10
GRISALES MESA EDWARD HERNAN;10
ROMERO BONILLA MARIN;10
DISTRIBUIDORA HERCA ASOCIADOS SAS;10
COOPERATIVA INTEGRAL DE TRANSPORTADORES TAXIS EL TRIUNFO;10
HOLGIN DIAZ ADALBERTO;10
WM FILTERS SAS;10
FILCENTER S A S;10
PRO-MOTORS S A S;10
PEREZ PLAZAS YILMER;10
LUBRIREPUESTOS YUMBO JRC S.A.S;10
RATIVA ORLANDO ALBERTO;10
TRACTOCAD S EN C S;10
AMAYA BERNAL VICTOR ANTONIO;10
GOMEZ CERON LUDIVIA;10
DISTRIBUCIONES ALVARO CORREA S.A.S.;10
LUBRICANTES PEPO S.A.S;10
INDUSTRIA SUPERFILT S.A.S;10
CERON OCHOA MAGNOLIA;10
LUBRICANTES Y FILTROS J J S.A.S;10
DISTRIBUIDORA IMALBESTOS SAS;10
LUBRIKARS S.A.S;10
VELASCO VEGA AURA STELLA;10
MAX OIL SAS;10
GASODISEL SABANA S.A.S;10
G C FILTERS SAS;10
GONZALEZ SALINAS EDWIN ARLEY;10
LUBRIPARTS LYL S.A.S;10
AUTOFILTROS Y PARTES GONZA MOTORS SAS;10
SERVILLANTAS JAMUNDI S.A.S;10
INGEFILTERS COLOMBIA SAS;10
HERRERA QUINTERO VICTOR ALONSO;10
LUBRICANTES DIDAMAR S.A.S;10
VARGAS SALAMANCA LUIS ANGEL;10
MARTEXA C I S A S;10
DACAR FILTROS S.A.S.;10
INVERSIONES BOGOTA MOTORS SAS;10
IBA EZ ALFONSO EFRAIN;10`;

// Función para normalizar claves de búsqueda
// Elimina tildes, ñ (la vuelve N o elimina según caso para matching fuzzy), y caracteres no alfanuméricos.
// Esto permite que "NIÑO" haga match con "NI O" o "NI O" con "NIO".
const normalizeKey = (str: string) => {
  return str.toUpperCase().replace(/[^A-Z0-9]/g, '');
};

const parseDataFromCSVs = (): { clients: Client[], points: ClientPoints[] } => {
  const clientsLines = RAW_CLIENTS_CSV.trim().split('\n');
  const pointsLines = RAW_POINTS_CSV.trim().split('\n');
  
  const clients: Client[] = [];
  const pointsMap = new Map<string, number>();

  // 1. Parsear Puntos y guardar en mapa con clave normalizada
  const pointsStart = pointsLines[0].startsWith('Punto de venta') ? 1 : 0;
  for (let i = pointsStart; i < pointsLines.length; i++) {
    const line = pointsLines[i].trim();
    if (!line) continue;
    const parts = line.split(';');
    if (parts.length >= 2) {
      const posName = parts[0].trim();
      const pts = parseInt(parts[1].trim()) || 0;
      // Guardamos usando la clave normalizada para tolerar fallos de encoding
      pointsMap.set(normalizeKey(posName), pts);
    }
  }

  // 2. Parsear Clientes y buscar sus puntos
  const clientsStart = clientsLines[0].startsWith('Tipo de cliente') ? 1 : 0;
  const points: ClientPoints[] = [];

  for (let i = clientsStart; i < clientsLines.length; i++) {
    const line = clientsLines[i].trim();
    if (!line) continue;
    
    const parts = line.split(';');
    // Now expecting 4 columns: Tipo; Id; Punto de venta; Contraseña
    if (parts.length >= 4) {
      const type = parts[0].trim() as ClientType;
      const businessId = parts[1].trim();
      const pointOfSale = parts[2].trim();
      const password = parts[3].trim();
      
      if (pointOfSale && password) {
        clients.push({
          id: `c_${i}`,
          businessId,
          pointOfSale,
          password,
          type
        });
        
        // Buscar puntos usando normalización del Nombre del Punto de Venta
        const normalizedPOS = normalizeKey(pointOfSale);
        const pts = pointsMap.get(normalizedPOS);

        points.push({
          pointOfSale,
          points: pts !== undefined ? pts : DEFAULT_POINTS
        });
      }
    }
  }
  return { clients, points };
};

const { clients: parsedClients, points: parsedPoints } = parseDataFromCSVs();

// Initial Seed Data
const INITIAL_DATA: Database = {
  clients: parsedClients,
  points: parsedPoints,
  rewards: [
    {
      id: 'rw_001',
      name: 'Camisetas COL',
      description: 'Póntela con orgullo, porque el partido también se juega con el corazón. Vestirse de selección es parte del ritual.',
      pointsPareto: 444,
      pointsNormal: 222,
      imageUrl: 'https://i.postimg.cc/QNp3mpDs/Camiseta-Seleccion-COL.avif'
    },
    {
      id: 'rw_002',
      name: 'Gorra / Vaso cervecero',
      description: 'Porque el hincha se reconoce desde el primer sorbo y hasta el último minuto. Para vivir el partido como se debe',
      pointsPareto: 89,
      pointsNormal: 44,
      imageUrl: 'https://placehold.co/600x400/002664/FFFFFF?text=Gorra+Gulf'
    },
    {
      id: 'rw_003',
      name: 'Balón original Selección Colombia',
      description: 'El balón que despierta sueños, pasiones y recuerdos de Mundial. Emocional y aspiracional.',
      pointsPareto: 256,
      pointsNormal: 128,
      imageUrl: 'https://placehold.co/600x400/002664/FFFFFF?text=Balon+Seleccion'
    },
    {
      id: 'rw_004',
      name: 'Sanduchera',
      description: 'Mientras rueda el balón, prepárate el sánduche del gol. Tal cual tu idea, perfecta y muy memorable.',
      pointsPareto: 144,
      pointsNormal: 72,
      imageUrl: 'https://placehold.co/600x400/002664/FFFFFF?text=Sanduchera'
    },
    {
      id: 'rw_005',
      name: 'Mini parrilla eléctrica',
      description: 'Cuando el partido se alarga, la parrilla también entra en la cancha. Perfecta para tiempos extra, reuniones y celebraciones.',
      pointsPareto: 89,
      pointsNormal: 44,
      imageUrl: 'https://placehold.co/600x400/002664/FFFFFF?text=Parrilla+Electrica'
    },
    {
      id: 'rw_006',
      name: 'Hielera',
      description: 'Que nada se caliente… ni el partido ni la bebida. Muy fútbol, muy reunión.',
      pointsPareto: 63,
      pointsNormal: 32,
      imageUrl: 'https://placehold.co/600x400/002664/FFFFFF?text=Hielera'
    },
    {
      id: 'rw_007',
      name: 'Parlante Bluetooth',
      description: 'Que el grito de gol se escuche en toda la casa. Esta frase es oro para volumen de puntos.',
      pointsPareto: 78,
      pointsNormal: 39,
      imageUrl: 'https://placehold.co/600x400/002664/FFFFFF?text=Parlante+BT'
    },
    {
      id: 'rw_008',
      name: 'Barra de sonido',
      description: 'Cada jugada, cada emoción, como si estuvieras al borde de la cancha. Eleva la experiencia del partido.',
      pointsPareto: 217,
      pointsNormal: 108,
      imageUrl: 'https://placehold.co/600x400/002664/FFFFFF?text=Barra+Sonido'
    },
    {
      id: 'rw_009',
      name: 'Televisor 45"',
      description: 'Vive cada partido como si estuvieras en la tribuna. Perfecta, directa y poderosa.',
      pointsPareto: 1000,
      pointsNormal: 500,
      imageUrl: 'https://placehold.co/600x400/002664/FFFFFF?text=TV+45+Pulgadas'
    },
    {
      id: 'rw_010',
      name: 'Televisor 55” – Gran premio',
      description: 'El Mundial no se mira… se vive en grande. Frase estrella, muy aspiracional.',
      pointsPareto: 1667,
      pointsNormal: 833,
      imageUrl: 'https://placehold.co/600x400/002664/FFFFFF?text=TV+55+Gran+Premio'
    }
  ]
};

// Helper to load/save from localStorage
export const getDatabase = (): Database => {
  const stored = localStorage.getItem(DB_KEY);
  if (!stored) {
    localStorage.setItem(DB_KEY, JSON.stringify(INITIAL_DATA));
    return INITIAL_DATA;
  }
  return JSON.parse(stored);
};

export const saveDatabase = (data: Database) => {
  localStorage.setItem(DB_KEY, JSON.stringify(data));
};

export const resetDatabase = (): Database => {
  localStorage.removeItem(DB_KEY);
  return getDatabase();
};

export const updateClientPoints = (pointOfSale: string, newPoints: number) => {
  const db = getDatabase();
  const index = db.points.findIndex(p => p.pointOfSale === pointOfSale);
  if (index !== -1) {
    db.points[index].points = newPoints;
    saveDatabase(db);
  }
};

export const deductPoints = (pointOfSale: string, amount: number): boolean => {
  const db = getDatabase();
  const clientPoints = db.points.find(p => p.pointOfSale === pointOfSale);
  
  if (clientPoints && clientPoints.points >= amount) {
    clientPoints.points -= amount;
    saveDatabase(db);
    return true;
  }
  return false;
};

export const getClients = () => getDatabase().clients;
export const getPoints = (pointOfSale: string) => getDatabase().points.find(p => p.pointOfSale === pointOfSale)?.points || 0;
export const getRewards = () => getDatabase().rewards;